apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gpts.fullname" . }}
  labels:
    {{- include "gpts.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gpts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gpts.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GPTS_SERVER_PORT
              value: {{ .Values.gpts.servicePort | default 80 | quote }}
            - name: GPTS_HEALTHCHECK_PORT
              value: {{ .Values.gpts.healthcheckPort | default 8000 | quote }}
            - name: GPTS_DEFAULT_CONFIG_ON_STARTUP
              value: {{ .Values.gpts.defaultConfigOnStartup | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.gpts.servicePort | default 80 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: {{ .Values.gpts.healthcheckPort | default 8000 }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.gpts.healthcheckPort | default 8000 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
