apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gpts.fullname" . }}
  labels:
    {{- include "gpts.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gpts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gpts.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.overrides.repository | default "ghcr.io" }}/{{ .Values.overrides.image | default "icikowski/gpts" }}:{{ .Values.overrides.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GPTS_SERVICE_PORT
              value: {{ .Values.gpts.servicePort | default 8080 | quote }}
            - name: GPTS_HEALTHCHECKS_PORT
              value: {{ .Values.gpts.healthchecksPort | default 8081 | quote }}
            - name: GPTS_CONFIG_ENDPOINT
              value: {{ .Values.gpts.configEndpoint | default "/config" | quote }}
            - name: GPTS_DEFAULT_CONFIG_ON_STARTUP
              value: {{ .Values.gpts.defaultConfigOnStartup | default "false" | quote }}
            - name: GPTS_LOG_LEVEL
              value: {{ .Values.gpts.logLevel | default "info" | quote }}
            - name: GPTS_PRETTY_LOG
              value: {{ .Values.gpts.prettyLog | default "false" | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.gpts.servicePort | default 8080 }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /live
              port: {{ .Values.gpts.healthchecksPort | default 8081 }}
            failureThreshold: 6
            periodSeconds: 5
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /live
              port: {{ .Values.gpts.healthchecksPort | default 8081 }}
            failureThreshold: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.gpts.healthchecksPort | default 8081 }}
            failureThreshold: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
