apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpts.fullname" . }}
  labels:
    {{- include "gpts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.gpts.servicePort | default 8080 }}
      protocol: TCP
      name: http
  selector:
    {{- include "gpts.selectorLabels" . | nindent 4 }}
